# Generated by Django 5.2.1 on 2025-05-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('high_severity', models.PositiveIntegerField(default=0)),
                ('medium_severity', models.PositiveIntegerField(default=0)),
                ('low_severity', models.PositiveIntegerField(default=0)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IPStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('anomaly_count', models.PositiveIntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_source', models.BooleanField(default=True)),
                ('protocols', models.JSONField(default=dict)),
                ('ports', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['-alert_count'], name='snort_analy_alert_c_b78055_idx'), models.Index(fields=['-anomaly_count'], name='snort_analy_anomaly_8861ea_idx'), models.Index(fields=['-last_seen'], name='snort_analy_last_se_f40753_idx')],
            },
        ),
        migrations.CreateModel(
            name='SnortAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.GenericIPAddressField()),
                ('destination_ip', models.GenericIPAddressField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_port', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('signature', models.CharField(max_length=255)),
                ('signature_id', models.PositiveIntegerField()),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('raw_log', models.TextField()),
                ('is_anomalous', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='snort_analy_timesta_566678_idx'), models.Index(fields=['source_ip'], name='snort_analy_source__b11ae1_idx'), models.Index(fields=['destination_ip'], name='snort_analy_destina_64f99a_idx'), models.Index(fields=['severity'], name='snort_analy_severit_7d9e9d_idx'), models.Index(fields=['is_anomalous'], name='snort_analy_is_anom_3c7be1_idx')],
            },
        ),
    ]
