# Generated by Django 5.2.1 on 2025-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ipstats',
            name='snort_analy_alert_c_b78055_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipstats',
            name='snort_analy_anomaly_8861ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='ipstats',
            name='snort_analy_last_se_f40753_idx',
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='anomaly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='ipstats',
            unique_together={('ip_address', 'is_source')},
        ),
    ]
