# Generated by Django 5.2.1 on 2025-05-27 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort_analyzer', '0002_remove_ipstats_snort_analy_alert_c_b78055_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='analyst', max_length=50)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ipstats',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='alert_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='anomaly_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AddIndex(
            model_name='ipstats',
            index=models.Index(fields=['-alert_count'], name='snort_analy_alert_c_b78055_idx'),
        ),
        migrations.AddIndex(
            model_name='ipstats',
            index=models.Index(fields=['-anomaly_count'], name='snort_analy_anomaly_8861ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ipstats',
            index=models.Index(fields=['-last_seen'], name='snort_analy_last_se_f40753_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snort_analyzer.snortalert'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
