# Generated by Django 5.2.1 on 2025-05-28 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort_analyzer', '0004_attacknotification_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipstats',
            name='alert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='anomaly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ipstats',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterUniqueTogether(
            name='ipstats',
            unique_together={('ip_address', 'is_source')},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snort_analyzer.snortalert')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
