# Generated by Django 5.2.1 on 2025-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort_analyzer', '0006_add_ml_prediction_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='snortalert',
            new_name='snort_analy_threat__7f1141_idx',
            old_name='snort_analy_threat_level_idx',
        ),
        migrations.RenameIndex(
            model_name='snortalert',
            new_name='snort_analy_ml_proc_393960_idx',
            old_name='snort_analy_ml_processed_idx',
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='ml_prediction',
            field=models.JSONField(blank=True, help_text='Complete ML prediction results including confidence and algorithm used', null=True),
        ),
    ]
