# Generated by Django 5.2.1 on 2025-08-03 20:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snort_analyzer', '0007_rename_snort_analy_threat_level_idx_snort_analy_threat__7f1141_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyStats',
        ),
        migrations.DeleteModel(
            name='IPStats',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_alert',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='attacknotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='snortalert',
            name='snort_analy_timesta_566678_idx',
        ),
        migrations.RemoveIndex(
            model_name='snortalert',
            name='snort_analy_source__b11ae1_idx',
        ),
        migrations.RemoveIndex(
            model_name='snortalert',
            name='snort_analy_destina_64f99a_idx',
        ),
        migrations.RemoveIndex(
            model_name='snortalert',
            name='snort_analy_severit_7d9e9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='snortalert',
            name='snort_analy_is_anom_3c7be1_idx',
        ),
        migrations.RemoveIndex(
            model_name='snortalert',
            name='snort_analy_threat__7f1141_idx',
        ),
        migrations.RemoveIndex(
            model_name='snortalert',
            name='snort_analy_ml_proc_393960_idx',
        ),
        migrations.RemoveField(
            model_name='attacknotification',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='snortalert',
            name='ml_prediction',
        ),
        migrations.RemoveField(
            model_name='snortalert',
            name='ml_processed',
        ),
        migrations.RemoveField(
            model_name='snortalert',
            name='threat_level',
        ),
        migrations.RemoveField(
            model_name='snortalert',
            name='threat_probability',
        ),
        migrations.AddField(
            model_name='attacknotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attacknotification',
            name='attack_type',
            field=models.CharField(default='Security Alert', max_length=100),
        ),
        migrations.AlterField(
            model_name='attacknotification',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AlterField(
            model_name='attacknotification',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='attacknotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='destination_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='destination_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='protocol',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='raw_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='severity',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='signature',
            field=models.CharField(default='No signature', max_length=500),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='signature_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='source_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='source_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snortalert',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
